# 在源仓库的 .github/workflows/sync-file.yml 中创建此工作流

name: Sync File to Another Repo

on:
  push:
    branches: [ main ]
    paths: 
      - 'data/clash.yaml'  # 仅当此文件变化时触发

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone target repo
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}  # 目标仓库的访问token
        run: |
          git clone https://x-access-token:${TARGET_TOKEN}@github.com/qjlxg/sub.git
          cd sub
          git pull origin main

      - name: Sync file
        run: |
          # 创建目标目录（如果不存在）
          mkdir -p sub/data
          # 强制复制文件
          cp -f data/clash.yaml sub/data/clash.yaml

      - name: Commit and push changes
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          cd 目标仓库名
          git add data/clash.yaml
          git commit -m "Sync clash.yaml from source repo (Commit: ${{ github.sha }})"
          git push https://x-access-token:${TARGET_TOKEN}@github.com/qjlxg/sub.git main
