name: Sync File to Another Repo

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'data/clash.yaml'

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone target repo
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${TARGET_TOKEN}@github.com/qjlxg/add.git
          cd add
          git pull origin main

      - name: Sync file
        run: |
          mkdir -p add/data
          cp -f data/clash.yaml add/data/clash.yaml
          cp -f data/clash.yaml add/data/all_clash.txt
          cp -f data/clash.yaml add/data/api.txt
          cp -f data/clash.yaml add/data/transporter.txt
          cp -f ./trial.yaml add/data/trial.yaml
          cp -f ./Long_term_subscription1.yaml add/data/Long_term_subscription1.yaml
          cp -f ./Long_term_subscription_num add/data/v2ray.txt

      - name: Commit and push changes
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          cd add
          git add data/  # 关键修复：添加 data 目录下所有文件
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${TARGET_TOKEN}@github.com/qjlxg/add.git main
